### ISSUE TITLE
Trouble with "Kubernetes bearer token authentication"

### ISSUE THREAD

**Issue by jynok** [devopsprodigy/kubegraf#10]
Hi,

I'm using Grafana v5.0.4 (commit: 7dc36ae) and kubegraf 1.1.0

When defining my cluster, I see the new "Bearer token access" label but ... nothing more (no checkbox):
![image](https://user-images.githubusercontent.com/55582496/65759889-41283a00-e11c-11e9-8568-a4c99a8ff6e0.png)

![image](https://user-images.githubusercontent.com/55582496/65759989-6fa61500-e11c-11e9-9b57-a3580e60a0cb.png)

Is there anything special to fill and/or configure to make the "Access via token" checkbox accessible? Feeling that I'm missing something obvious...

Thanks a lot!

JYC

**Comment by SergeiSporyshev** [comment]
Hi!
Thank you for issue
Fixed 
https://github.com/devopsprodigy/kubegraf/releases/tag/v1.1.1

**Comment by jynok** [comment]
Thanks @SergeiSporyshev.

Tried 1.1.1 and now have the Access via token checkbox and token field available :-)

But now I'm facing another issue, data source creation fails (Data source is not OK is displayed).

In logs, I have the following:

t=2019-10-01T07:57:22+0000 lvl=info msg=Requesting logger=data-proxy-log url=%7B%7B%20.JsonData.cluster_url%20%7D%7D/api/v1/namespaces
2019/10/01 07:57:22 http: proxy error: unsupported protocol scheme ""

Will try to dig deeper into this new issue and open another ticket if I don't find the solution.

**Comment by jynok** [comment]
OK, correct me if I'm wrong but I think dynamic routes (that you're using for access via token) are not supported in Grafana 5; that would explain why the url hasn't been replaced by the value coming from jsonData ^_^

I'll try this again if/when we'll be able to move to Grafana 6. 

Thanks again for your plugin and help (even if it seems what you did to support the checkbox for Grafana 5 has been somehow a waste, sorry for that).
