### ISSUE TITLE
Node CPU/RAM utilization metrics are missing

### ISSUE THREAD

**Issue by amravyan** [devopsprodigy/kubegraf#15]
Hi!

Node CPU/RAM utilization metrics are missing after plugin update to latest version (8371dafcf01bdc75ad1d9382df08d06ccb0420e7 -> d55e55174f65222555f511f11f070bf07df32263).

Please investigate it and fix if possible.

![image](https://user-images.githubusercontent.com/34545055/68943527-7c5df580-07bc-11ea-9185-2297686cdf1b.png)

**Comment by SergeiSporyshev** [comment]
Hi! Thank you for this issue.
We are working on this bug right now

**Comment by SergeiSporyshev** [comment]
Hi!
Fixed)
https://github.com/devopsprodigy/kubegraf/releases/tag/v1.2.0
