### ISSUE TITLE
recommended prometheus configuration

### ISSUE THREAD

**Issue by filip-havlicek** [devopsprodigy/kubegraf#16]
Hi,

do you have recommended configuration for Prometheus?
We have our own configuration and some graphs doesn't work in your dashboards. Probably because of missing metrics, labels..

Thank You.

**Comment by SergeiSporyshev** [comment]
Hi!
Thank you for issue!

We prefer prometheus-operator's configuration.
But in release v1.2 (https://github.com/devopsprodigy/kubegraf/releases/tag/v1.2.0.7) we tried to improve the compatibility with different configurations.

Which version of plugin do you use?

**Comment by filip-havlicek** [comment]
Hi, thank you for your response.
Formerly 1.1.1 from official grafana repository.
But in the meantime I tested v1.2.0.7 and I made some tweaks in our Prometheus configuration and everything looks fine now.
So from my point of view, everything is fine and you can close this issue.
But maybe it's not a bad idea to have some minimal/default recommended configuration for Prometheus (maybe just copy configmap from prometheus-operator..) in your repository. At least people can compare their configuration to one which works.

**Comment by SergeiSporyshev** [comment]
Hi @filip-havlicek!
We plan to add helm charts for deploying this plugin with Grafana and Prometheus.
But adding some configuration files to the this repo and readme is a good idea
Thank you

**Comment by SergeiSporyshev** [comment]
Hi @filip-havlicek!
We added example config https://github.com/devopsprodigy/kubegraf/tree/master/prometheus
