### ISSUE TITLE
View tabs rendering issue

### ISSUE THREAD

**Issue by Demon-DK** [devopsprodigy/kubegraf#18]
Source data
------------------------
Firefox: 70.0
Grafana 6.3.5
Kubernetes 1.15
Kube-state-metrics: 1.8.0
Kubegraf 1.1.1

Issue description
------------------------
The image below will say more than a thousand words  :)
- This rendering issue relevant to all tabs of the plugin.
- All add-blockers are switched off

![image](https://user-images.githubusercontent.com/25489257/70238188-7a5ed500-1771-11ea-9f06-24c7d7c9c845.png)

**Comment by SergeiSporyshev** [comment]
Hi!
Thank you for this issue

**Comment by SergeiSporyshev** [comment]
Hi, @Demon-DK 
Pls, check this release
https://github.com/devopsprodigy/kubegraf/releases/tag/v1.2.0.11

**Comment by Demon-DK** [comment]
> 
> 
> Hi, @Demon-DK
> Pls, check this release
> https://github.com/devopsprodigy/kubegraf/releases/tag/v1.2.0.11

Hi,
Yes, it's resolved with the latest fix,
Thanks !
