### ISSUE TITLE
Cluster overview tab queries issue

### ISSUE THREAD

**Issue by Demon-DK** [devopsprodigy/kubegraf#19]
Source data
------------------------
Kubegraf 1.1.1
Grafana 6.3.5
Kubernetes 1.15.3
Prometheus 2.12.0
Kube-state-metrics: 1.8.0

Issue description
------------------------
There are some issue in plugin query in the cluster overview tab (see screen below)
- Alert list displays the same node for all three cases and same time at the right side for this node we see different reasons for the alerting related to memory consumption but with absolutely different memory data.
- More likely only the first case is correct because mentioned in list node has 18Gb of memory.
- And also your separate out of the box dashboard "DevOpsProdigy KubeGraf Node's Dashboard" display everything right for this node

![image](https://user-images.githubusercontent.com/25489257/70395870-fbd19400-1a0b-11ea-963b-b1da3ca94a67.png)

**Comment by SergeiSporyshev** [comment]
Hi! Thank you for this issue.
We will check this page

**Comment by SergeiSporyshev** [comment]
Hi, @Demon-DK 
Pls, check this release
https://github.com/devopsprodigy/kubegraf/releases/tag/v1.2.0.11

**Comment by Demon-DK** [comment]
Hi, @SergeiSporyshev 

Actually don't quite sure if it's fixed correct:
- Instead three alerts I see now only one
- It is displaying with the right node name
- But I see only alert related to second row in my screen
(_My cluster behavior hasn't changed since yesterday_)

**Comment by SergeiSporyshev** [comment]
Hi, @Demon-DK!
Can you show your alerts' table and all of node's tables from node's overview page?

**Comment by Demon-DK** [comment]
Hi, @SergeiSporyshev 

Yes, sure

Here they are:
![image](https://user-images.githubusercontent.com/25489257/70580022-0d0cd300-1bbb-11ea-9f49-ce4e9e0fba1a.png)

I think no need to screen all pages cause I guess you have wanted to verify alarms with that which are alarmed in "Node's overview". I've checked attentively all and there are only one in alarm state
![image](https://user-images.githubusercontent.com/25489257/70580161-768ce180-1bbb-11ea-9c94-73c29550cb80.png)

BTW I would suggest to change default or implement in future editable threshold settings. Because performing an alarm only for 51 percent of memory usage it's actually to early.
Because especially in this case this is Elasticsearch node and it will never consume lower memory than 50%
Thus I will watch this alarm an eternity.

**Comment by SergeiSporyshev** [comment]
Ok, i understand you!
Can we close this issue?

**Comment by Demon-DK** [comment]
Hi, @SergeiSporyshev 

Yes, sure, thanks
