### ISSUE TITLE
Plugin version on grafana.com is old

### ISSUE THREAD

**Issue by timwebster9** [devopsprodigy/kubegraf#20]
If you follow your instructions and do:
```
grafana-cli plugins install devopsprodigy-kubegraf-app
```
You end up with v1.1.1 of the plugin, which is the latest version hosted on grafana.com.  Are there any plans to keep that repo up to date with your latest releases?

I actually use the Grafana Helm chart method, where you can just do this
```
plugins:
  - devopsprodigy-kubegraf-app
```
but this has the same effect and only installs the latest version hosted in `https://grafana.com/api/plugins/devopsprodigy-kubegraf-app/versions`

**Comment by SergeiSporyshev** [comment]
Hi!
We have a PR to grafana-plugin-repo (https://github.com/grafana/grafana-plugin-repository/pull/520) with version 1.2.0
But sometimes merges of PR are too long

**Comment by timwebster9** [comment]
Ok thanks. I think I'm getting something similar to #14, so wanted the latest version.

Also - do you know if there is a way to configure your plugin with code?  I don't want to use a storage volume (don't need long-term data), and would like to not have to reconfigure the plugin every time the pod is re-deployed...

**Comment by SergeiSporyshev** [comment]
I think it's impossible, because grafana store configuration of plugins in SQLite DB (/var/lib/grafana/grafana.db)

**Comment by SergeiSporyshev** [comment]
Hi @timwebster9 !
We have a new version of our plugin in Grafana' store
Check it)

**Comment by timwebster9** [comment]
@SergeiSporyshev nice - I just quickly tried it and although I'm not getting the `NaN` stuff anymore there is a lot of 'no data', especially for pod/container metrics.  I need to dig into it to figure out why.

FYI I'm running this on microk8s v1.17.0 and the 'master' version of Prometheus (so I can get the new temperature metrics)

**Comment by timwebster9** [comment]
OK so the reason it's not working is because the fields are different in my metrics.  For example the query for pod memory usage looks like this:
```
sum (container_memory_usage_bytes{namespace="$namespace", pod_name="$pod", container_name!="", container_name!="POD", container_name=~"$containers"})
```
for this I get no results, plus I get a warning on the edit page: `Time series is monotonically increasing. Try applying a rate() function.`

If I change it to this it works fine:
```
container_memory_usage_bytes{namespace="$namespace", pod="$pod"}
```
In my data I have `pod` instead of `pod_name`, and I don't have any of those `container` fields in the data.  All I have is this:
```
container_memory_usage_bytes{beta_kubernetes_io_arch="arm64",beta_kubernetes_io_os="linux",id="/kubepods/besteffort/pode2ac9a3b-1d7f-47a5-9f17-81c6cbfcc500",instance="io",job="kubernetes-nodes-cadvisor",kubernetes_io_arch="arm64",kubernetes_io_hostname="io",kubernetes_io_os="linux",microk8s_io_cluster="true",namespace="unbound",pod="unbound-58fd6c6fc4-5qhw9"}
```
Is this plugin written for a specific version of k8s and Prometheus?

**Comment by SergeiSporyshev** [comment]
Check your prometheus' config
We have example config in our repo (https://github.com/devopsprodigy/kubegraf/blob/master/prometheus/config.example.yml) - like prometheus-operator's config
