### ISSUE TITLE
Cluster list not appear

### ISSUE THREAD

**Issue by osmufe** [devopsprodigy/kubegraf#25]
Hi Guys,

If use the latest version of Kube Graf and Grafana (v6.6.0) , fails the when access to cluster list , not appear .

Thanks

**Comment by SergeiSporyshev** [comment]
Hi, thank you for your issue.
Can you make a screenshot with error or give a messages from browser's console?

**Comment by SergeiSporyshev** [comment]
Hi, @osmufe 
It'is a bug of Grafana v6.6.0, which exists in a lot plugins (for example - https://github.com/raintank/worldping-app/issues/233)
Try to update your Grafana version to v6.6.1

**Comment by osmufe** [comment]
Thanks  a lot , I Upgrade to 6.6.1 and now works fine.
