### ISSUE TITLE
Data not visible in some panels in devopsprodigy-kubegraf-nodes-dashboard

### ISSUE THREAD

**Issue by forumsheth15** [devopsprodigy/kubegraf#32]
Hi , I have installed this plugin and configured it with my Kubernetes cluster details.
I am able to see data in all other dashboards other than the nodes dashboard.
![image](https://user-images.githubusercontent.com/51082137/85274576-c159b100-b49c-11ea-9fe6-7fd6ca395a86.png)

Can anyone help me with this?

**Comment by SergeiSporyshev** [comment]
Hi, @forumsheth15 
try to install plugin from repo with tag v1.4.1
We have just deployed & created PR to plugin repository

**Comment by forumsheth15** [comment]
Hi @SergeiSporyshev  can you tell me when will the plugin be updated with 1.4.1 version, to install it directly using the grafana-cli. As I tried to install it from repo but unable to clone the git repo inside the pod.

**Comment by forumsheth15** [comment]
Hi @SergeiSporyshev  can you please help me with this issue?

**Comment by SergeiSporyshev** [comment]
@forumsheth15 
what is the version of your node-exporter, do yo have node-exporter's metrics in your Prometheus?

**Comment by forumsheth15** [comment]
Hi @SergeiSporyshev Yes i was able to see node-exporter metrics.
But later on deploying the latest version of node-exporter the issue was resolved.
Thank you
