### ISSUE TITLE
Cant load deleted pods metrics in pod dashboard

### ISSUE THREAD

**Issue by vizdrag** [devopsprodigy/kubegraf#33]
Grafana v7.0.3
Kubegraf v1.4.0
Kubernetes v1.17.3
Prometheus Operator 8.13.7
Dashboard: DevOpsProdigy KubeGraf Pod's Dashboard
I want to view info about pod's that deleted. Label named "containers" block it
![image](https://user-images.githubusercontent.com/24516746/85390555-a5fcad80-b551-11ea-960d-a2a75d74dad7.png)
I mean that issue blocks all graphs besides IOPS graph

**Comment by SergeiSporyshev** [comment]
Hi, @vizdrag 
Thank you for your issue.
We are working on this bug right now

**Comment by SergeiSporyshev** [comment]
Hi, @vizdrag 
Can you check plugin from this release https://github.com/devopsprodigy/kubegraf/releases/tag/v1.4.2 ?

**Comment by vizdrag** [comment]
That's it! Thank you =)
