### ISSUE TITLE
Clusters Page breaks since Grafana v7.0.4

### ISSUE THREAD

**Issue by dotressel** [devopsprodigy/kubegraf#35]
The `Clusters` page, that lists all configured clusters, does not work properly in Grafana 7.0.4 and later versions. The layout and styling seems to be broken.

**Comment by SergeiSporyshev** [comment]
Hi, @dotressel
Thank your for your issue
We will deploy fix soon

**Comment by SergeiSporyshev** [comment]
Hi, @dotressel 
Check plugin from this release - https://github.com/devopsprodigy/kubegraf/releases/tag/v1.4.2

**Comment by dotressel** [comment]
Perfect, fixed it for us! Thank you!!
