### ISSUE TITLE
Pod Limit, CPU, Memory shows double data

### ISSUE THREAD

**Issue by forumsheth15** [devopsprodigy/kubegraf#36]
Hi @SergeiSporyshev on the Node Overview page, the Used and Requested Pod Limits, CPU and Memory shows double the count as on the cluster. 
Below are the screenshots for referrence:
1. kubectl describe node <node>
![image](https://user-images.githubusercontent.com/51082137/87636692-ba9e2100-c75e-11ea-8f7b-b3d9a888597f.png)
![image](https://user-images.githubusercontent.com/51082137/87636853-fa650880-c75e-11ea-8eb7-f2e676a9355d.png)

2. Node Overview page
![image](https://user-images.githubusercontent.com/51082137/87636787-e3261b00-c75e-11ea-9bc9-efec976930de.png)

If you see the images..the pod count from describing the node is 15 and on the overview page it shows 30.
Likewise for CPU and Memory.
Can you please look in to the issue and let me know why is it so?

**Comment by SergeiSporyshev** [comment]
Hi, @forumsheth15 
Thanks for your issue

What is your prometheus installation?
Seems like you have duplicate targets

**Comment by forumsheth15** [comment]
Hi @SergeiSporyshev Thanks for pointing out, yes there were two targets with same configuration which were scarping same data.
I have deleted one and now I can see proper data.
Thankyou the issue is solved now.

**Comment by forumsheth15** [comment]
Hi @SergeiSporyshev I am again facing the same issue with CPU and Memory. The pod count is fixed now.
I have a scrape config job of kube-state-metrics and kubernetes-service-endpoints , both of these are scarping the same data for CPU and Memory... On removing kubernetes-service-endpoints job the CPU and Memory data was fixed but some of my other data went missing on the Node Overview page, So I have to keep both the scrape config jobs.
Also the same data of CPU and Memory on the DevOpsProdigy KubeGraf Node's Dashboard is showing proper data.
The issue is only with the Node Overview page.
![image](https://user-images.githubusercontent.com/51082137/87786873-5cedff80-c858-11ea-9334-292f872a58bf.png)
![image](https://user-images.githubusercontent.com/51082137/87787056-a4748b80-c858-11ea-81f5-4c52b17a51b1.png)
![image](https://user-images.githubusercontent.com/51082137/87787113-bc4c0f80-c858-11ea-8614-1e3e5cc09f99.png)
