### ISSUE TITLE
access GKE cluster

### ISSUE THREAD

**Issue by viberan** [devopsprodigy/kubegraf#4]
Is there a way to configure authentication for k8s cluster on GKE?
thanks

**Comment by rgershkovich** [comment]
@SergeiSporyshev, can you please clarify what you mean by `http-access`?
In GKE there is no access to cluster CA, so it's impossible to issue a client certificate. An option would be to grab a token from some ServiceAccount, but AFAIS the plugin doesn't support this way of authentication.

**Comment by feadosiy** [comment]
Have the same issue with access to GKE

**Comment by SergeiSporyshev** [comment]
https://github.com/devopsprodigy/kubegraf/releases/tag/v1.1.0

**Comment by feadosiy** [comment]
I still don't see any possibility for GKE connection.
Could you please clarify a little bit ?

**Comment by kSandr-ki** [comment]
Парни нихрена не пашет )
