### ISSUE TITLE
Only Admins see "Clusters list"

### ISSUE THREAD

**Issue by phidlipus** [devopsprodigy/kubegraf#54]
After upgrade from v1.4.2 to v1.5.0.4 only users with role Admin see the Clusters list.
In 1.4.2 also users with Editor and Viewer see the Clusters list. 
It would be nice to bring back the possibility to view Clusters list for regular users.

Kubegraf: 1.5.0.4
Grafana: 6.5.3

![image](https://user-images.githubusercontent.com/2934244/107248217-5e6c5880-6a32-11eb-85d3-6a94b177b3da.png)

**Comment by Zauxst** [comment]
It would be nice to actually get a user access list and manage who gets to get access to the views.
We have observed this issue as well today.

**Comment by SergeiSporyshev** [comment]
Hi! Thanks for your issue. Investigating that right now

**Comment by SergeiSporyshev** [comment]
Hi, @Zauxst @phidlipus 
This issue fixed in the our latest release - https://github.com/devopsprodigy/kubegraf/releases/tag/v1.5.1

Already published

**Comment by phidlipus** [comment]
It works. Thank you!
