### ISSUE TITLE
kube-state-metrics depreciated metrics referenced by kubegraf 1.5.1

### ISSUE THREAD

**Issue by jon-eicher** [devopsprodigy/kubegraf#55]
Kubegraf 1.5.1 is currently referencing metrics which kube-state-metrics has removed.  This breaks the Node Dashboard's graph.

Here is a link showing the depreciated metrics:
https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md

These metrics are no longer valid after kube-state-metrics v2.0.0-alpha
kube_node_status_capacity_pods
kube_node_status_capacity_cpu_cores
kube_node_status_capacity_memory_bytes
kube_node_status_allocatable_pods
kube_node_status_allocatable_cpu_cores
kube_node_status_allocatable_memory_bytes
kube_pod_container_resource_requests_cpu_cores
kube_pod_container_resource_limits_cpu_cores
kube_pod_container_resource_requests_memory_bytes
kube_pod_container_resource_limits_memory_bytes

Here are some screenshots for a visual:

Node Dashboard:
![Screen Shot 2021-03-05 at 9 27 32 AM](https://user-images.githubusercontent.com/71353830/110144059-263c0980-7d95-11eb-8305-19efe996b34b.png)

Grafana query for the Node Dashboard:
![Screen Shot 2021-03-05 at 9 21 04 AM](https://user-images.githubusercontent.com/71353830/110144134-39e77000-7d95-11eb-8be8-b70ec2867844.png)

List of removed kube-state-metrics, metrics:
![Screen Shot 2021-03-05 at 9 20 35 AM](https://user-images.githubusercontent.com/71353830/110144207-51265d80-7d95-11eb-94bf-3448e2950c22.png)

**Comment by SergeiSporyshev** [comment]
Hi, @jon-eicher 
Thanks for your issue
Will investigate this asap

**Comment by SergeiSporyshev** [comment]
Hi, @jon-eicher 
We fixed that in the our latest release - https://github.com/devopsprodigy/kubegraf/releases/tag/v1.5.2
