### ISSUE TITLE
Some of node's metrics are missing on Nodes overview tab

### ISSUE THREAD

**Issue by amravyan** [devopsprodigy/kubegraf#9]
Hi!

Facing a strange issue: some of node's metrics (pod limits usage percent, for example) are missing on the tab _Nodes overview_ (N/A NaN%). On the other hand, all these metrics are available in prometheus.
Could you please check and investigate? All screenshots are attached.

**Kubernetes** v1.15.3 (on-premise, kubespray)
**Prometheus**  from helm chart stable/prometheus (9.1.1), **node-exporter image** prom/node-exporter:v0.18.0

![prom_data_mem](https://user-images.githubusercontent.com/34545055/65503120-ecdb4b00-decc-11e9-84ae-bf8fd2b7198a.jpg)
![prom_data_cpu](https://user-images.githubusercontent.com/34545055/65503121-ecdb4b00-decc-11e9-89ef-b17c832d7774.jpg)
![metrics](https://user-images.githubusercontent.com/34545055/65503122-ecdb4b00-decc-11e9-87cd-3092a39e17de.jpg)

**Comment by SergeiSporyshev** [comment]
Hi!
It's look like Prometheus cann't scrape metrics from kubelet (/metrics/cadvisor)

**Comment by amravyan** [comment]
In case you have Prometheus installed from **bare prometheus chart** (not prometheus operator), you have to add label replace rule listed below to two jobs: _kubernetes-nodes_ and _kubernetes-nodes-cadvisor_.

```
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: node

```
![image](https://user-images.githubusercontent.com/34545055/66634196-38a02b00-ec15-11e9-8c0d-8361c8b385d1.png)
